# Use an official Node.js runtime based on Node.js 20 and Alpine
FROM --platform=linux/amd64 node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install npm dependencies inside the container
RUN npm install

# Copy the entire application source code from the local filesystem to the filesystem of the container
COPY . .

# Expose the port that the application runs on
EXPOSE 3000

# Specify the command to run the application
CMD [ "npm", "start" ]
